version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/code/"
    schedule:
      interval: "weekly"
    # Ignore updates for tought-cookie
    ignore:
      - dependency-name: "tough-cookie"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
    
